name: Release Pipeline

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up GitHub token for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Set git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build project
        run: npm run build

      - name: Copy build output to releases/version folder
        run: |
          mkdir -p releases/${{ steps.get_version.outputs.version }}
          cp -r dist/* releases/${{ steps.get_version.outputs.version }}/

      - name: Commit releases folder
        run: |
          git add releases/
          git commit -m "chore: add release for v${{ steps.get_version.outputs.version }}" || echo "No changes to commit"

      - name: Push releases folder
        run: |
          git push origin master 